import axios from "axios";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

type CategoryType = {
  id: number;
  attributes: {
    name: string;
    slug: string;
  };
};

type CategoriesPageProps = {
  categories: CategoryType[];
};

const Categories: NextPage<CategoriesPageProps> = (props) => {
  const { categories } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Categories!</h1>

        <p className={styles.description}></p>

        <div className={styles.grid}>
          {categories.map((category: CategoryType) => (
            <div key={category.id} className={styles.card}>
              <h2>{category.attributes.name}</h2>
              <p>See the categories list.</p>
              <p>{category.attributes.slug}</p>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        Powered by{" "}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </footer>
    </div>
  );
};

export default Categories;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { data: categories } = await axios.get(
    "https://neogrid-strapi.herokuapp.com/api/categories"
  );

  return {
    props: {
      categories: categories.data,
    },
  };
};
