import axios from "axios";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

type PostType = {
  id: number;
  attributes: {
    title: string;
    slug: string;
  };
};

type PostsPageProps = {
  posts: PostType[];
  time: number;
};

const Posts: NextPage<PostsPageProps> = (props) => {
  const { posts } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Posts!</h1>

        <p className={styles.description}></p>

        <div className={styles.grid}>
          {posts.map((post: PostType) => (
            <div key={post.id} className={styles.card}>
              <h2>{post.attributes.title}</h2>
              <p>See the categories list.</p>
              <p>{post.attributes.slug}</p>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        Powered by{" "}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </footer>
    </div>
  );
};

export default Posts;

export const getStaticProps: GetStaticProps = async (context) => {
  const { data: posts } = await axios.get(
    "https://neogrid-strapi.herokuapp.com/api/posts"
  );

  return {
    props: {
      posts: posts.data,
      time: new Date().getTime(),
    },
    revalidate: 30, // em segundos
  };
};
